# Generated by Django 6.0.7 on 2026-07-15 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MockBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('logo_url', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#000000', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50)),
                ('iban', models.CharField(max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('account_type', models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings')], default='checking', max_length=20)),
                ('label', models.CharField(default='حساب جارٍ', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='api.mockbank')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=255)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit (دائن/دخل)'), ('debit', 'Debit (مدين/مصروف)')], max_length=10)),
                ('category', models.CharField(choices=[('salary', 'راتب أساسي'), ('freelance', 'عمل حر'), ('investments', 'عوائد استثمار'), ('rent', 'إيجار سكن'), ('car_loan', 'تمويل سيارة'), ('utilities', 'فاتورة كهرباء/مياه'), ('subscription', 'اشتراك سحابي/ترفيهي'), ('groceries', 'بقالة ومعيشة'), ('shopping', 'تسوق/أخرى'), ('dining', 'مطاعم وكافيهات')], max_length=30)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.userbankaccount')),
            ],
        ),
    ]
